### ISSUE TITLE
指出两个地方的问题

### ISSUE THREAD

**Issue by Coderii** [Josin22/JSDownloadView#1]
1. 你的progress进度判断是否完成，不能跟1.00直接比较的
2. 重复点击（先等第一次按了之后进度出来之后然后一直按一直按）出现了BUG了，你可以试一下

**Comment by Josin22** [comment]
@Coderii   我是按照下载中的数据占百分比来作为progress来传进度的,下载完成的百分比只可能为1吧,
你说的重复点击我还没想好是下载中把enable关闭还是怎样?给个建议吧~

**Comment by fendoukobe** [comment]
有一个疑问，
- (CAAnimationGroup *)getLineToPointUpAnimationWithValues:(NSArray *)values
这个由线到点 外加上弹的动画中设置 CASpringAnimation *lineUpAnimation的toValue lineUpAnimation.toValue = @6; 这里的toValue不应该是0吗，6这个值又是如何计算得来的呢？因为是跳到顶点位置
，但是我设置了之后，发现这个点已经跳到圆圈之外了，能否解惑一下？谢谢～

**Comment by ericchuhong** [comment]
我觉得应该是线变点的过程中enable关掉，然后在progress的过程中enable开启，然后点击的话会让动画暂停，再点击动画继续。

**Comment by Josin22** [comment]
@ericchuhong  👌
