### ISSUE TITLE
lineUpAnimation.toValue = @6的计算

### ISSUE THREAD

**Issue by fendoukobe** [Josin22/JSDownloadView#2]
有一个疑问，
- (CAAnimationGroup *)getLineToPointUpAnimationWithValues:(NSArray *)values
  这个由线到点 外加上弹的动画中设置 CASpringAnimation *lineUpAnimation的toValue lineUpAnimation.toValue = @6; 这里的toValue不应该是0吗，6这个值又是如何计算得来的呢？因为是跳到顶点位置
  ，但是我设置了之后，发现这个点已经跳到圆圈之外了，能否解惑一下？谢谢～

**Comment by Josin22** [comment]
@fendoukobe  _verticalLineLayer.frame = [self bounds];为了好计算,我把线的frame同JSDownloadView一样,所以变成点的时候其实是中心点,你可以尝试在verticalLineLayer懒加载的时候填一句代码":_verticalLineLayer.backgroundColor = [UIColor redColor].CGColor;就可以看到效果

**Comment by fendoukobe** [comment]
还不是很明白，_verticalLineLayer变成点的时候，position应该是（50，44），当执行动画CASpringAnimation *lineUpAnimation = [CASpringAnimation animationWithKeyPath: keyPath_PositionY];
    lineUpAnimation.toValue = @6;_verticalLineLayer应该是整个向上偏移了38，这个时候_verticalLineLayer不是应该还在在圆圈内吗

**Comment by fendoukobe** [comment]
嗯，ineUpAnimation.toValue = @6应该是慢慢调试出来的吧，产生的动画效果是同设置的动画属性（mass,dampimg, initialVelocity,toValue等）都有关联，

**Comment by Josin22** [comment]
@fendoukobe mass越大弹的动作越大
