### ISSUE TITLE
下载波浪线结束时调整高度是否会更加平滑

### ISSUE THREAD

**Issue by ericchuhong** [Josin22/JSDownloadView#4]
我修改了以下代码，加入了一个高度的函数，这样波浪线结束时是不是会更加平滑。
`
- (void)setProgress:(CGFloat)progress{  
  ...
  CGFloat progressWaveHeight = -12.0 \* powf(_progress, 2) + 12 \* _progress;
  //浪
  [self waveWithHeight:_progress < 0.5 ? _waveHeight : progressWaveHeight];
  ...
  ｝

// -(void)wave {} 方法修改为
- (void)waveWithHeight:(CGFloat)waveHeight {
  
  self.offset += self.waveSpeed;
  
  self.arrowLayer.path = [self.service getWavePathWithOffset:self.offset
                                                  WaveHeight:waveHeight
                                               WaveCurvature:self.waveCurvature].CGPath;

}
`
![downloadergif](https://cloud.githubusercontent.com/assets/5848572/18432269/a0ee52cc-7913-11e6-85ca-1a6258047074.gif)

**Comment by Josin22** [comment]
多谢建议,已加入代码

**Comment by chinhiyoshi** [comment]
thanks
