### ISSUE TITLE
iPhone5 8.4闪退

### ISSUE THREAD

**Issue by huangboju** [Josin22/JSDownloadView#5]

**Comment by Josin22** [comment]
@huangboju  xcode几?

**Comment by huangboju** [comment]
7.3.1

**Comment by Josin22** [comment]
我这边运行咋没事嘞?

**Comment by huangboju** [comment]
<img width="1280" alt="2016-09-14 8 19 52" src="https://cloud.githubusercontent.com/assets/14818224/18495911/0ff40a04-7a54-11e6-8d82-4d5e2cad08f5.png">

**Comment by Josin22** [comment]
initialVelocity是CASpringAnimation的属性,但是报了没识别发送的对象错误,注释试试~
