### ISSUE TITLE
pod 没找到？

### ISSUE THREAD

**Issue by bulolo** [Josin22/JSDownloadView#9]
pod 没找到？

**Comment by bulolo** [comment]
Installing JSDownloadView (1.0.0)

[!] Error installing JSDownloadView
[!] /usr/bin/git clone https://github.com/Josin22/JSDownloadView.git /var/folders/1f/wnv_4m7x1nj6m1g2pvl3v9dc0000gn/T/d20170206-3635-1w5yvej --template= --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/1f/wnv_4m7x1nj6m1g2pvl3v9dc0000gn/T/d20170206-3635-1w5yvej'...
warning: Could not find remote branch 1.0.0 to clone.
fatal: Remote branch 1.0.0 not found in upstream origin

**Comment by Josin22** [comment]
pod 'JSDownloadView', '~> 1.0.2'
